"use client";
import {useEffect,useState} from "react";
import {BarChart3,FlaskConical,RefreshCw,FileText,Plug,Check,Download,ClipboardCheck} from "lucide-react";
import {api,Governance} from "@/lib/api";
import {CodeEvaluation,CodeEvaluationResult} from "./code-evaluation";
import {FactEvaluation,FactEvaluationResult} from "./fact-evaluation";
import {AnswerReviewPanel} from "./answer-review-panel";
import {AnswerComparisonPanel} from "./answer-comparison";
import {AnswerEvaluationSetsPanel} from "./answer-evaluation-sets";

type Case={id:string;query?:string;passed:boolean;checks?:Record<string,boolean>;recommendation?:string;expected?:string[];retrieved?:string[];precision?:number|null;recall?:number|null;mrr?:number|null};
type Batch={id:string;dataset:string;fingerprint:string;created_at:string;results:{description:string;scope:string;runner_revision:string;passed:number;total:number;elapsed_ms:number;analysis:Case[];retrieval:Record<string,{rows:Case[];mean:{precision:number;recall:number;mrr:number};passed:number;total:number}>;code_retrieval?:CodeEvaluationResult;source_facts?:FactEvaluationResult;ragas?:{provider:string;version:string;rows:{variant:string;case_id:string;context_recall:number;context_precision:number}[]}}};
type Metric={run_id:string;question:string;status:string;mode:string;measured:boolean;complete:boolean;historical_prefix:boolean;attempts:number;model_calls:number;elapsed_ms:number|null;known_input_tokens:number;known_output_tokens:number;unknown_usage_calls:number;estimated_cost:string|null;currency:string|null;usage_complete:boolean};
type Report={id:string;week_start:string;body:string;source_run_ids:string[];document_id:string|null;created_by:string;fingerprint:string};
type Status={dataset:string;case_count?:number;week_start:string;ragas_available:boolean;mcp_enabled:boolean;mcp_transport:string;scope:string};
const names:Record<string,string>={lease:"后台租约",index:"索引失效",approval:"审批失效",abstention:"无命中时不编造", "pr-risk":"危险 PR", "pr-isolation":"PR 提交隔离","ci-failure":"失败 CI","issue-triage":"Issue 分诊"};
const checks:Record<string,string>={evidence_present:"来源证据存在",citations_valid:"引用合法",has_scope_limits:"说明来源范围",recommendation:"决策符合样例",risk:"风险级别",observed_error:"保留实际错误"};
function percent(value:number|null|undefined){return value===null||value===undefined?"—":`${(value*100).toFixed(1)}%`;}
function date(value:string){return new Date(/[Z]|[+-]\d{2}:\d{2}$/.test(value)?value:value+"Z").toLocaleString("zh-CN",{timeZone:"Asia/Shanghai"});}

export function DeliveryPanel({repositoryId}:{repositoryId:string}){
  const root=`/repositories/${repositoryId}`;
  const [reviewRunId,setReviewRunId]=useState("");
  const [tab,setTab]=useState("evaluation"),[status,setStatus]=useState<Status|null>(null),[permissions,setPermissions]=useState<Governance|null>(null),[metrics,setMetrics]=useState<Metric[]>([]),[batches,setBatches]=useState<Batch[]>([]),[reports,setReports]=useState<Report[]>([]),[selected,setSelected]=useState(""),[reportId,setReportId]=useState(""),[week,setWeek]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const refresh=async()=>{const [s,p,m,b,r]=await Promise.all([api<Status>(root+"/delivery/status"),api<Governance>(root+"/governance"),api<{runs:Metric[]}>(root+"/metrics"),api<Batch[]>(root+"/evaluations"),api<Report[]>(root+"/reports")]);setStatus(s);setPermissions(p);setMetrics(m.runs);setBatches(b);setReports(r);setWeek(w=>w||s.week_start);};
  useEffect(()=>{void refresh().catch(e=>setError(e.message));},[repositoryId]); // eslint-disable-line react-hooks/exhaustive-deps
  const change=async(path:string,body?:object)=>{if(busy)return;setBusy(true);setError("");setNotice("");try{const result=await api<{id:string}>(path,{method:"POST",...(body?{body:JSON.stringify(body)}:{})});if(path.endsWith("/evaluations"))setSelected(result.id);if(path.endsWith("/reports"))setReportId(result.id);await refresh();setNotice("结果已保存，可以查看历史记录。");}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const batch=batches.find(b=>b.id===selected)||batches[0],report=reports.find(r=>r.id===reportId)||reports[0];
  const measured=metrics.filter(m=>m.measured),tokens=metrics.reduce((sum,m)=>sum+m.known_input_tokens+m.known_output_tokens,0);
  return <div className="governance-layout"><section className="panel governance-intro"><div><p className="eyebrow">EVALUATE & DELIVER</p><h2>验证每次改动，留下可复查的结果。</h2><p>固定样例检验规则与检索，运行记录保存真实用量，周报汇总已有分析。阶段 5 正在建设。</p></div><FlaskConical size={32}/></section>
    <div className="governance-toolbar"><span className="tag">{status?.dataset||"加载中…"}</span><span className="small-muted">本地评测 · 不调用外部模型</span><button className="button secondary" disabled={busy} onClick={()=>{setError("");void refresh().catch(e=>setError(e.message));}}><RefreshCw size={14}/>刷新</button></div>
    {error&&<p role="alert" className="governance-error">{error}</p>}{notice&&<p role="status" className="review-note">{notice}</p>}
    <div className="governance-tabs" role="tablist" aria-label="评测与交付分类">{[{id:"evaluation",label:"固定评测",icon:FlaskConical},{id:"answers",label:"回答评审",icon:ClipboardCheck},{id:"comparison",label:"回答对照",icon:ClipboardCheck},{id:"samples",label:"评估样本集",icon:ClipboardCheck},{id:"metrics",label:"耗时与用量",icon:BarChart3},{id:"reports",label:"分析周报",icon:FileText},{id:"mcp",label:"MCP 扩展",icon:Plug}].map(t=><button role="tab" aria-selected={tab===t.id} className={tab===t.id?"selected":""} key={t.id} onClick={()=>setTab(t.id)}><t.icon size={15}/>{t.label}</button>)}</div>
    <fieldset className="governance-content" disabled={busy}>
      {tab==="answers"&&<AnswerReviewPanel key={repositoryId} repositoryId={repositoryId} canReview={!!permissions?.can_review} initialRunId={reviewRunId}/>}
      {tab==="comparison"&&<AnswerComparisonPanel key={repositoryId} repositoryId={repositoryId} canRun={!!permissions?.can_edit}/>}
      {tab==="samples"&&<AnswerEvaluationSetsPanel key={repositoryId} repositoryId={repositoryId} canCreate={!!permissions?.can_edit} onReview={id=>{setReviewRunId(id);setTab("answers");}}/>}
      {tab==="evaluation"&&<><section className="panel governance-card"><div className="panel-heading"><h3>{status?.case_count||8} 条固定样例</h3>{permissions?.can_edit&&<button className="button primary" onClick={()=>change(root+"/evaluations")}>{busy?"运行中…":"运行固定评测"}</button>}</div><p>检查文档与源码检索、引用、PR 风险、CI 与来源范围。保留旧策略作对照；样例结果不代表真实模型质量。</p>{batches.length>0&&<label className="delivery-select">评测记录<select aria-label="选择评测记录" value={batch?.id||""} onChange={e=>setSelected(e.target.value)}>{batches.map(b=><option key={b.id} value={b.id}>{date(b.created_at)} · {b.dataset} · {b.results.passed}/{b.results.total} · {b.id.slice(0,8)}</option>)}</select></label>}</section>
      {batch&&<><section className="panel governance-card"><div className="panel-heading"><h3>{batch.results.passed} / {batch.results.total} 样例通过</h3><span className="tag">{batch.results.elapsed_ms} ms</span></div><p className="small-muted">数据版本 {batch.fingerprint.slice(0,12)} · 实现版本 {batch.results.runner_revision.slice(0,12)}</p><div className="delivery-table-scroll"><table className="delivery-table"><thead><tr><th>检索策略</th><th>Precision@2</th><th>Recall@2</th><th>MRR@2</th></tr></thead><tbody>{Object.entries(batch.results.retrieval).map(([key,r])=><tr key={key}><td>{key==="bm25"?"BM25":"标题关键词基线"}</td><td>{percent(r.mean.precision)}</td><td>{percent(r.mean.recall)}</td><td>{percent(r.mean.mrr)}</td></tr>)}</tbody></table></div><p className="small-muted">均值只含 3 条有标准来源的检索样例；另 1 条验证无命中时不编造。</p><div className="delivery-cases">{[...batch.results.retrieval.bm25.rows,...batch.results.analysis].map(c=><details key={c.id}><summary><span className={`tag ${c.passed?"review-approved":"review-rejected"}`}>{c.passed?"通过":"未通过"}</span>{names[c.id]||c.id}</summary>{c.query&&<p>{c.query} · 命中 {c.retrieved?.join(", ")||"无"}</p>}{c.checks&&<p>{Object.entries(c.checks).map(([k,v])=>`${checks[k]||k}：${v?"通过":"未通过"}`).join(" · ")}</p>}</details>)}</div></section>
      {batch.results.code_retrieval&&<CodeEvaluation result={batch.results.code_retrieval}/>}
      {batch.results.source_facts&&<FactEvaluation result={batch.results.source_facts}/>}
      <section className="panel governance-card"><div className="panel-heading"><h3>Ragas 检索指标</h3>{permissions?.can_edit&&<button className="button secondary" disabled={!status?.ragas_available||!!batch.results.ragas} onClick={()=>change(root+`/evaluations/${batch.id}/ragas`)}>{batch.results.ragas?"已保存指标":"计算 Ragas 指标"}</button>}</div><p>使用 Ragas 的非 LLM 指标比较文档召回上下文与标准上下文，关闭遥测。源码指标独立按路径和行段评分；当前不测模型忠实度或答案语义质量。</p>{!status?.ragas_available&&<p className="review-note">需要按 README 安装隔离的评测环境。</p>}{batch.results.ragas&&<div className="delivery-table-scroll"><table className="delivery-table"><thead><tr><th>策略</th><th>Context recall</th><th>Context precision</th></tr></thead><tbody>{["title_keyword","bm25"].map(v=>{const rows=batch.results.ragas!.rows.filter(r=>r.variant===v);return <tr key={v}><td>{v==="bm25"?"BM25":"标题关键词基线"}</td><td>{percent(rows.reduce((s,r)=>s+r.context_recall,0)/rows.length)}</td><td>{percent(rows.reduce((s,r)=>s+r.context_precision,0)/rows.length)}</td></tr>;})}</tbody></table></div>}<a className="text-button" href={`/api${root}/evaluations/${batch.id}/export`} target="_blank" rel="noreferrer"><Download size={14}/>查看文档评测数据 JSON</a></section></>}{!batch&&<p className="empty-small">尚无评测记录。运行固定样例后查看对照结果。</p>}</>}
      {tab==="metrics"&&<><section className="panel governance-card"><h3>最近 30 次运行</h3><div className="delivery-stats"><div><strong>{measured.length}</strong><span>已记录耗时的运行</span></div><div><strong>{metrics.reduce((s,m)=>s+m.model_calls,0)}</strong><span>已记录模型请求</span></div><div><strong>{tokens.toLocaleString()}</strong><span>已记录输入 + 输出 Token</span></div></div><p className="small-muted">从 v0.7 开始记录。旧运行用量无法补算；失败请求可能已计费但没有返回用量。价格未配置时费用显示未知。</p></section>{metrics.map(m=><article className="panel governance-card" key={m.run_id}><div className="panel-heading"><h3>{m.question.slice(0,100)}</h3><span className="tag">{m.run_id.slice(0,8)}</span></div><p className="small-muted">{m.status} · {m.mode} · {m.measured?`${m.attempts} 次记录的执行`:"历史执行未测量"}</p>{m.measured?<div className="delivery-stats"><div><strong>{m.elapsed_ms===null?"执行未结束":`${(m.elapsed_ms/1000).toFixed(2)} s`}</strong><span>执行耗时，不含排队</span></div><div><strong>{m.known_input_tokens} / {m.known_output_tokens}</strong><span>已知输入 / 输出 Token</span></div><div><strong>{m.estimated_cost===null?"未知":`${m.estimated_cost} ${m.currency||""}`}</strong><span>配置价格下的估算费用</span></div></div>:<p className="review-note">历史运行未记录用量和耗时，不能据此判定费用为零。</p>}{(m.unknown_usage_calls>0||m.historical_prefix)&&<p className="review-note">{m.unknown_usage_calls>0?`${m.unknown_usage_calls} 次请求没有完整用量。`:"恢复前的历史执行未记录用量。"}仅展示已知部分，费用不可完整估算。</p>}</article>)}</>}
      {tab==="reports"&&<><section className="panel governance-card"><h3>生成分析周报</h3><p>按北京时间周一至周日，汇总本仓库已保存且完成的分析。来源和待确认项随报告保留。</p>{permissions?.can_edit&&<form className="governance-form" onSubmit={e=>{e.preventDefault();void change(root+"/reports",{week_start:week});}}><label>开始日期（周一）<input aria-label="周报开始日期" type="date" value={week} onChange={e=>setWeek(e.target.value)} required/></label><button className="button primary">生成本地周报</button></form>}{reports.length>0&&<label className="delivery-select">历史周报<select aria-label="选择周报" value={report?.id||""} onChange={e=>setReportId(e.target.value)}>{reports.map(r=><option key={r.id} value={r.id}>{r.week_start} · {r.source_run_ids.length} 次分析 · {r.id.slice(0,8)}</option>)}</select></label>}</section>{report&&<section className="panel governance-card"><div className="panel-heading"><h3>{report.week_start} · 分析周报</h3><span className="tag">{report.document_id?"已存入知识库":"待确认"}</span></div><p className="small-muted">{report.source_run_ids.length} 次来源分析 · {report.created_by} · {report.fingerprint.slice(0,12)}</p><pre className="delivery-report">{report.body}</pre><div className="governance-actions">{permissions?.can_review&&<button className="button primary" disabled={!!report.document_id} onClick={()=>change(root+`/reports/${report.id}/publish-knowledge`)}><Check size={15}/>{report.document_id?"已存入知识库":"确认并存入知识库"}</button>}<button className="text-button" onClick={()=>navigator.clipboard.writeText(report.body)}>复制周报</button></div><p className="small-muted">存入当前仓库的本地文档库，供后续检索；不会发送 GitHub 或其他应用。</p></section>}</>}
      {tab==="mcp"&&<section className="panel governance-card"><div className="panel-heading"><h3>只读 MCP 服务</h3><span className="tag">{status?.mcp_enabled?"当前仓库已配置":"尚未启用授权"}</span></div><p>通过 stdio 提供 6 个工具：仓库快照、文档检索、批准记忆检索、已保存分析、代码片段和分析周报。</p><p>独立 Token 与仓库 ID 白名单限制访问。MCP 无权发起模型分析、创建草稿、审批或发布。</p><p className="small-muted">仓库 ID：{repositoryId}</p><pre className="delivery-report">{`# backend/.env 配置独立随机 Token（至少 32 位）\nMCP_ACCESS_TOKEN=自行生成的独立Token\nMCP_REPOSITORY_IDS=${repositoryId}\n\n# 从项目根目录启动 stdio 服务\n.\\scripts\\start-mcp.ps1`}</pre><p className="small-muted">配置后重启 API 和 MCP。当前 SDK 握手、工具调用及权限隔离已通过独立测试；默认配置没有向其他应用开放仓库。</p></section>}
    </fieldset>
  </div>;
}
